<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="css/xterm.min.css" rel="stylesheet" type="text/css"/>
    <link href="css/fullscreen.min.css" rel="stylesheet" type="text/css"/>
    <link rel="shortcut icon" href="favicon.png">
    <title>Cloud Terminal</title>
</head>
<body>
<h2 style="position: fixed;z-index: 10000;color: white;top: 0;right: 2%;">Cloud Terminal</h2>
<div id="terminal"></div>
<script src="js/jquery.min.js"></script>
<script src="js/xterm.min.js"></script>
<script src="js/fullscreen.min.js"></script>
<script src="js/main.js"></script>
</body>
</html>
